# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EncimaTco.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaTco(object):
    def setupUi(self, VentanaTco):
        VentanaTco.setObjectName("VentanaTco")
        VentanaTco.setEnabled(True)
        VentanaTco.resize(1191, 731)
        VentanaTco.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        VentanaTco.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(VentanaTco)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(880, 120, 301, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 40, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.Tinicial = QtWidgets.QLineEdit(self.groupBox)
        self.Tinicial.setGeometry(QtCore.QRect(60, 40, 81, 20))
        self.Tinicial.setObjectName("Tinicial")
        self.Tfinal = QtWidgets.QLineEdit(self.groupBox)
        self.Tfinal.setGeometry(QtCore.QRect(210, 40, 81, 20))
        self.Tfinal.setObjectName("Tfinal")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.Minicial = QtWidgets.QLineEdit(self.groupBox)
        self.Minicial.setGeometry(QtCore.QRect(60, 100, 81, 20))
        self.Minicial.setObjectName("Minicial")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(170, 100, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.Mfinal = QtWidgets.QLineEdit(self.groupBox)
        self.Mfinal.setGeometry(QtCore.QRect(210, 100, 81, 20))
        self.Mfinal.setObjectName("Mfinal")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(110, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setScaledContents(False)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(80, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setScaledContents(False)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 100, 161, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.field = QtWidgets.QComboBox(self.groupBox_2)
        self.field.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.field.setObjectName("field")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.column = QtWidgets.QComboBox(self.groupBox_2)
        self.column.setGeometry(QtCore.QRect(10, 100, 141, 22))
        self.column.setObjectName("column")
        self.loaded = QtWidgets.QLabel(self.groupBox_2)
        self.loaded.setGeometry(QtCore.QRect(120, 130, 31, 21))
        self.loaded.setText("")
        self.loaded.setPixmap(QtGui.QPixmap("../Img/puntorojo.png"))
        self.loaded.setScaledContents(True)
        self.loaded.setObjectName("loaded")
        self.buttonloaded = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonloaded.setGeometry(QtCore.QRect(10, 130, 91, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/cargar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonloaded.setIcon(icon)
        self.buttonloaded.setIconSize(QtCore.QSize(30, 30))
        self.buttonloaded.setObjectName("buttonloaded")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(710, 390, 291, 231))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.aboveTco = QtWidgets.QLabel(self.groupBox_5)
        self.aboveTco.setGeometry(QtCore.QRect(30, 30, 91, 21))
        self.aboveTco.setAlignment(QtCore.Qt.AlignCenter)
        self.aboveTco.setObjectName("aboveTco")
        self.belowTco = QtWidgets.QLabel(self.groupBox_5)
        self.belowTco.setGeometry(QtCore.QRect(150, 30, 91, 21))
        self.belowTco.setAlignment(QtCore.Qt.AlignCenter)
        self.belowTco.setObjectName("belowTco")
        self.aboveTco_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.aboveTco_2.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.aboveTco_2.setObjectName("aboveTco_2")
        self.aboveTco_2.addItem("")
        self.aboveTco_2.addItem("")
        self.aboveTco_2.addItem("")
        self.aboveTco_2.addItem("")
        self.belowTco_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.belowTco_2.setGeometry(QtCore.QRect(150, 60, 121, 22))
        self.belowTco_2.setObjectName("belowTco_2")
        self.tco1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.tco1.setGeometry(QtCore.QRect(20, 90, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tco1.setFont(font)
        self.tco1.setObjectName("tco1")
        self.tco2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.tco2.setGeometry(QtCore.QRect(20, 120, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tco2.setFont(font)
        self.tco2.setObjectName("tco2")
        self.exportcsv = QtWidgets.QPushButton(self.groupBox_5)
        self.exportcsv.setGeometry(QtCore.QRect(170, 190, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportcsv.sizePolicy().hasHeightForWidth())
        self.exportcsv.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportcsv.setIcon(icon1)
        self.exportcsv.setIconSize(QtCore.QSize(30, 30))
        self.exportcsv.setAutoRepeatDelay(295)
        self.exportcsv.setAutoDefault(False)
        self.exportcsv.setDefault(False)
        self.exportcsv.setFlat(False)
        self.exportcsv.setObjectName("exportcsv")
        self.line = QtWidgets.QFrame(self.groupBox_5)
        self.line.setGeometry(QtCore.QRect(10, 140, 261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(150, 160, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.calcular = QtWidgets.QPushButton(self.groupBox_5)
        self.calcular.setGeometry(QtCore.QRect(10, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.calcular.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Img/Calcular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calcular.setIcon(icon2)
        self.calcular.setObjectName("calcular")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(710, 120, 153, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.Datoinicialzfc = QtWidgets.QLineEdit(self.groupBox_4)
        self.Datoinicialzfc.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.Datoinicialzfc.setObjectName("Datoinicialzfc")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(37, 60, 81, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.Datofinalzfc = QtWidgets.QLineEdit(self.groupBox_4)
        self.Datofinalzfc.setGeometry(QtCore.QRect(30, 90, 91, 20))
        self.Datofinalzfc.setObjectName("Datofinalzfc")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 50, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.Masa = QtWidgets.QLineEdit(self.centralwidget)
        self.Masa.setGeometry(QtCore.QRect(450, 50, 81, 20))
        self.Masa.setObjectName("Masa")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(880, 270, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.Distanciainterplanar = QtWidgets.QLineEdit(self.groupBox_8)
        self.Distanciainterplanar.setGeometry(QtCore.QRect(210, 20, 81, 20))
        self.Distanciainterplanar.setObjectName("Distanciainterplanar")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(210, 580, 461, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.size_x_min = QtWidgets.QLineEdit(self.groupBox_7)
        self.size_x_min.setGeometry(QtCore.QRect(140, 20, 71, 20))
        self.size_x_min.setObjectName("size_x_min")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(100, 20, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(100, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.size_y_min = QtWidgets.QLineEdit(self.groupBox_7)
        self.size_y_min.setGeometry(QtCore.QRect(140, 50, 71, 20))
        self.size_y_min.setObjectName("size_y_min")
        self.size_x_max = QtWidgets.QLineEdit(self.groupBox_7)
        self.size_x_max.setGeometry(QtCore.QRect(270, 20, 71, 20))
        self.size_x_max.setObjectName("size_x_max")
        self.size_y_max = QtWidgets.QLineEdit(self.groupBox_7)
        self.size_y_max.setGeometry(QtCore.QRect(270, 50, 71, 20))
        self.size_y_max.setObjectName("size_y_max")
        self.Button_Set = QtWidgets.QPushButton(self.groupBox_7)
        self.Button_Set.setGeometry(QtCore.QRect(360, 30, 81, 23))
        self.Button_Set.setAutoDefault(False)
        self.Button_Set.setDefault(False)
        self.Button_Set.setFlat(False)
        self.Button_Set.setObjectName("Button_Set")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(230, 20, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(230, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.Button_Zoom = QtWidgets.QPushButton(self.groupBox_7)
        self.Button_Zoom.setGeometry(QtCore.QRect(20, 20, 71, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Img/zoom.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Zoom.setIcon(icon3)
        self.Button_Zoom.setIconSize(QtCore.QSize(20, 20))
        self.Button_Zoom.setObjectName("Button_Zoom")
        self.savePicture = QtWidgets.QPushButton(self.groupBox_7)
        self.savePicture.setGeometry(QtCore.QRect(20, 60, 71, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Img/guardar_figura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePicture.setIcon(icon4)
        self.savePicture.setIconSize(QtCore.QSize(20, 20))
        self.savePicture.setObjectName("savePicture")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(1060, 600, 111, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../Img/Uptc_Logo.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.Logo_GFM = QtWidgets.QLabel(self.centralwidget)
        self.Logo_GFM.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.Logo_GFM.setText("")
        self.Logo_GFM.setPixmap(QtGui.QPixmap("../Img/GSM.jpg"))
        self.Logo_GFM.setScaledContents(True)
        self.Logo_GFM.setObjectName("Logo_GFM")
        self.Logo_Telematics = QtWidgets.QLabel(self.centralwidget)
        self.Logo_Telematics.setGeometry(QtCore.QRect(1030, 30, 151, 71))
        self.Logo_Telematics.setTabletTracking(False)
        self.Logo_Telematics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Logo_Telematics.setAcceptDrops(False)
        self.Logo_Telematics.setText("")
        self.Logo_Telematics.setPixmap(QtGui.QPixmap("../Img/Telematics.png"))
        self.Logo_Telematics.setScaledContents(True)
        self.Logo_Telematics.setObjectName("Logo_Telematics")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(480, 20, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 270, 161, 161))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.reportes = QtWidgets.QPushButton(self.groupBox_3)
        self.reportes.setGeometry(QtCore.QRect(20, 30, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportes.sizePolicy().hasHeightForWidth())
        self.reportes.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Img/report.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportes.setIcon(icon5)
        self.reportes.setIconSize(QtCore.QSize(30, 30))
        self.reportes.setAutoRepeatDelay(295)
        self.reportes.setAutoDefault(False)
        self.reportes.setDefault(False)
        self.reportes.setFlat(False)
        self.reportes.setObjectName("reportes")
        self.btnenviar = QtWidgets.QPushButton(self.groupBox_3)
        self.btnenviar.setGeometry(QtCore.QRect(20, 70, 121, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Img/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnenviar.setIcon(icon6)
        self.btnenviar.setIconSize(QtCore.QSize(25, 25))
        self.btnenviar.setAutoDefault(False)
        self.btnenviar.setDefault(False)
        self.btnenviar.setFlat(False)
        self.btnenviar.setObjectName("btnenviar")
        self.dataBase = QtWidgets.QPushButton(self.groupBox_3)
        self.dataBase.setGeometry(QtCore.QRect(20, 120, 121, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Img/Database.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataBase.setIcon(icon7)
        self.dataBase.setIconSize(QtCore.QSize(30, 30))
        self.dataBase.setAutoDefault(False)
        self.dataBase.setDefault(False)
        self.dataBase.setFlat(False)
        self.dataBase.setObjectName("dataBase")
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 440, 161, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.resultados = QtWidgets.QTextBrowser(self.groupBox_6)
        self.resultados.setGeometry(QtCore.QRect(20, 30, 121, 161))
        self.resultados.setObjectName("resultados")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(710, 260, 153, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.Datoinicialfc = QtWidgets.QLineEdit(self.groupBox_9)
        self.Datoinicialfc.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.Datoinicialfc.setObjectName("Datoinicialfc")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setGeometry(QtCore.QRect(37, 60, 81, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.Datofinalfc = QtWidgets.QLineEdit(self.groupBox_9)
        self.Datofinalfc.setGeometry(QtCore.QRect(30, 80, 91, 20))
        self.Datofinalfc.setObjectName("Datofinalfc")
        self.Muestra = QtWidgets.QLineEdit(self.centralwidget)
        self.Muestra.setGeometry(QtCore.QRect(930, 90, 81, 20))
        self.Muestra.setObjectName("Muestra")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(820, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(190, 90, 511, 491))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.TableDataset = QtWidgets.QTableWidget(self.groupBox_10)
        self.TableDataset.setGeometry(QtCore.QRect(20, 40, 491, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.TableDataset.sizePolicy().hasHeightForWidth())
        self.TableDataset.setSizePolicy(sizePolicy)
        self.TableDataset.setShowGrid(True)
        self.TableDataset.setWordWrap(True)
        self.TableDataset.setCornerButtonEnabled(True)
        self.TableDataset.setObjectName("TableDataset")
        self.TableDataset.setColumnCount(3)
        self.TableDataset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TableDataset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.TableDataset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TableDataset.setHorizontalHeaderItem(2, item)
        self.TableDataset.horizontalHeader().setDefaultSectionSize(153)
        self.TableDataset.horizontalHeader().setMinimumSectionSize(30)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_10)
        self.graphicsView.setGeometry(QtCore.QRect(20, 210, 491, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.graphicsView.setFont(font)
        self.graphicsView.setObjectName("graphicsView")
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setGeometry(QtCore.QRect(210, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(210, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.fecha = QtWidgets.QLabel(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(50, 660, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.fecha.setFont(font)
        self.fecha.setText("")
        self.fecha.setObjectName("fecha")
        VentanaTco.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaTco)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1191, 21))
        self.menubar.setObjectName("menubar")
        VentanaTco.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaTco)
        self.statusbar.setObjectName("statusbar")
        VentanaTco.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaTco)
        QtCore.QMetaObject.connectSlotsByName(VentanaTco)
        VentanaTco.setTabOrder(self.field, self.Tinicial)
        VentanaTco.setTabOrder(self.Tinicial, self.Tfinal)
        VentanaTco.setTabOrder(self.Tfinal, self.Minicial)
        VentanaTco.setTabOrder(self.Minicial, self.Mfinal)
        VentanaTco.setTabOrder(self.Mfinal, self.Masa)
        VentanaTco.setTabOrder(self.Masa, self.size_x_min)
        VentanaTco.setTabOrder(self.size_x_min, self.size_x_max)
        VentanaTco.setTabOrder(self.size_x_max, self.size_y_min)
        VentanaTco.setTabOrder(self.size_y_min, self.size_y_max)
        VentanaTco.setTabOrder(self.size_y_max, self.Datoinicialzfc)
        VentanaTco.setTabOrder(self.Datoinicialzfc, self.Datofinalzfc)
        VentanaTco.setTabOrder(self.Datofinalzfc, self.column)
        VentanaTco.setTabOrder(self.column, self.Distanciainterplanar)
        VentanaTco.setTabOrder(self.Distanciainterplanar, self.graphicsView)
        VentanaTco.setTabOrder(self.graphicsView, self.aboveTco_2)
        VentanaTco.setTabOrder(self.aboveTco_2, self.tco1)
        VentanaTco.setTabOrder(self.tco1, self.belowTco_2)
        VentanaTco.setTabOrder(self.belowTco_2, self.tco2)
        VentanaTco.setTabOrder(self.tco2, self.Button_Set)
        VentanaTco.setTabOrder(self.Button_Set, self.reportes)
        VentanaTco.setTabOrder(self.reportes, self.dataBase)
        VentanaTco.setTabOrder(self.dataBase, self.calcular)

    def retranslateUi(self, VentanaTco):
        _translate = QtCore.QCoreApplication.translate
        VentanaTco.setWindowTitle(_translate("VentanaTco", "MainWindow"))
        self.groupBox.setTitle(_translate("VentanaTco", "TC"))
        self.label_4.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:12pt;\">T</span><span style=\" font-size:12pt; vertical-align:sub;\">i</span></p></body></html>"))
        self.label_5.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:12pt;\">T</span><span style=\" font-size:12pt; vertical-align:sub;\">f</span></p></body></html>"))
        self.label_6.setText(_translate("VentanaTco", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">ii</span></p></body></html>"))
        self.label_7.setText(_translate("VentanaTco", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">ff</span></p></body></html>"))
        self.label_22.setText(_translate("VentanaTco", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00007f;\">Normal phase</span></p></body></html>"))
        self.label_23.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" color:#00007f;\">Superconductor phase</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("VentanaTco", "Dataset"))
        self.label.setText(_translate("VentanaTco", "Fields"))
        self.label_2.setText(_translate("VentanaTco", "Columns"))
        self.buttonloaded.setText(_translate("VentanaTco", "Load"))
        self.groupBox_5.setTitle(_translate("VentanaTco", "CRITICAL PARAMETERS"))
        self.aboveTco.setText(_translate("VentanaTco", "Above Tco"))
        self.belowTco.setText(_translate("VentanaTco", "Below Tco"))
        self.aboveTco_2.setItemText(0, _translate("VentanaTco", "ZFC"))
        self.aboveTco_2.setItemText(1, _translate("VentanaTco", "Tc"))
        self.aboveTco_2.setItemText(2, _translate("VentanaTco", "Tirr"))
        self.aboveTco_2.setItemText(3, _translate("VentanaTco", "Tco"))
        self.tco1.setText(_translate("VentanaTco", "Tco-1"))
        self.tco2.setText(_translate("VentanaTco", "Tco-2"))
        self.exportcsv.setText(_translate("VentanaTco", "csv"))
        self.label_24.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" color:#00007f;\">Export Data</span></p></body></html>"))
        self.calcular.setText(_translate("VentanaTco", "Compute"))
        self.groupBox_4.setTitle(_translate("VentanaTco", "ZFC"))
        self.label_8.setText(_translate("VentanaTco", "Inicial date"))
        self.label_9.setText(_translate("VentanaTco", "Final Date"))
        self.label_3.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sample Mass m(g)</span></p></body></html>"))
        self.label_16.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-weight:600;\">Interplanar Distance s(m)</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("VentanaTco", "Size Graph"))
        self.label_18.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">X</span><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">i</span></p></body></html>"))
        self.label_19.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Y</span><span style=\" font-size:11pt; font-weight:600; vertical-align:sub;\">i</span></p></body></html>"))
        self.Button_Set.setText(_translate("VentanaTco", "Set"))
        self.label_21.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">X</span><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">i</span></p></body></html>"))
        self.label_20.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Y</span><span style=\" font-size:11pt; font-weight:600; vertical-align:sub;\">f</span></p></body></html>"))
        self.Button_Zoom.setText(_translate("VentanaTco", "Zoom"))
        self.savePicture.setText(_translate("VentanaTco", "Save"))
        self.label_17.setText(_translate("VentanaTco", "DATA ENTRY"))
        self.groupBox_3.setTitle(_translate("VentanaTco", "Report"))
        self.reportes.setText(_translate("VentanaTco", "Reports"))
        self.btnenviar.setText(_translate("VentanaTco", "Send Data"))
        self.dataBase.setText(_translate("VentanaTco", "DataBase"))
        self.groupBox_6.setTitle(_translate("VentanaTco", "Statistics"))
        self.groupBox_9.setTitle(_translate("VentanaTco", "FC"))
        self.label_10.setText(_translate("VentanaTco", "Inicial date"))
        self.label_11.setText(_translate("VentanaTco", "Final Date"))
        self.label_12.setText(_translate("VentanaTco", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Sample Name</span></p></body></html>"))
        self.groupBox_10.setTitle(_translate("VentanaTco", "Display"))
        item = self.TableDataset.horizontalHeaderItem(0)
        item.setText(_translate("VentanaTco", "Temperature (K)"))
        item = self.TableDataset.horizontalHeaderItem(1)
        item.setText(_translate("VentanaTco", "Magnetic Field (Oe)"))
        item = self.TableDataset.horizontalHeaderItem(2)
        item.setText(_translate("VentanaTco", "Moment (emu)"))
        self.label_14.setText(_translate("VentanaTco", "Display Dataset"))
        self.label_15.setText(_translate("VentanaTco", "Display Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaTco = QtWidgets.QMainWindow()
    ui = Ui_VentanaTco()
    ui.setupUi(VentanaTco)
    VentanaTco.show()
    sys.exit(app.exec_())
