# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reportes.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(721, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/Telematica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(560, 550, 131, 61))
        self.label.setLineWidth(1)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Img/Uptc_Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 20, 141, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Img/Telematics.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 81, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Img/GSM.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(170, 50, 361, 31))
        self.label_4.setObjectName("label_4")
        self.tableaboveTco = QtWidgets.QTableWidget(Dialog)
        self.tableaboveTco.setGeometry(QtCore.QRect(50, 120, 641, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableaboveTco.setFont(font)
        self.tableaboveTco.setAutoFillBackground(True)
        self.tableaboveTco.setRowCount(5)
        self.tableaboveTco.setColumnCount(11)
        self.tableaboveTco.setObjectName("tableaboveTco")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableaboveTco.setItem(1, 0, item)
        self.tableaboveTco.horizontalHeader().setDefaultSectionSize(113)
        self.tablebelowTco = QtWidgets.QTableWidget(Dialog)
        self.tablebelowTco.setGeometry(QtCore.QRect(50, 350, 641, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tablebelowTco.setFont(font)
        self.tablebelowTco.setRowCount(5)
        self.tablebelowTco.setColumnCount(7)
        self.tablebelowTco.setObjectName("tablebelowTco")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 320, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.exportopdf = QtWidgets.QPushButton(Dialog)
        self.exportopdf.setGeometry(QtCore.QRect(340, 560, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.exportopdf.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../fisica/Interfaz-Fisica/Img/Importardata.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportopdf.setIcon(icon1)
        self.exportopdf.setObjectName("exportopdf")
        self.saveDatabase = QtWidgets.QPushButton(Dialog)
        self.saveDatabase.setGeometry(QtCore.QRect(140, 560, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.saveDatabase.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Img/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveDatabase.setIcon(icon2)
        self.saveDatabase.setObjectName("saveDatabase")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Results Critical Parameters"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Results Critical Parameters </span></p></body></html>"))
        __sortingEnabled = self.tableaboveTco.isSortingEnabled()
        self.tableaboveTco.setSortingEnabled(False)
        self.tableaboveTco.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Dialog", "AboveTc0"))
        self.label_6.setText(_translate("Dialog", "BelowTc0"))
        self.exportopdf.setText(_translate("Dialog", "Export to pdf"))
        self.saveDatabase.setText(_translate("Dialog", "Save Database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
