# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(713, 469)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 371, 136))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Description = QtWidgets.QPushButton(self.centralwidget)
        self.Description.setGeometry(QtCore.QRect(220, 250, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Description.setFont(font)
        self.Description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Description.setObjectName("Description")
        self.DataEntry = QtWidgets.QPushButton(self.centralwidget)
        self.DataEntry.setGeometry(QtCore.QRect(220, 200, 271, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataEntry.sizePolicy().hasHeightForWidth())
        self.DataEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DataEntry.setFont(font)
        self.DataEntry.setObjectName("DataEntry")
        self.SoftwareDescription = QtWidgets.QPushButton(self.centralwidget)
        self.SoftwareDescription.setGeometry(QtCore.QRect(220, 300, 271, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SoftwareDescription.sizePolicy().hasHeightForWidth())
        self.SoftwareDescription.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SoftwareDescription.setFont(font)
        self.SoftwareDescription.setObjectName("SoftwareDescription")
        self.Abbreviations = QtWidgets.QPushButton(self.centralwidget)
        self.Abbreviations.setGeometry(QtCore.QRect(220, 350, 271, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Abbreviations.sizePolicy().hasHeightForWidth())
        self.Abbreviations.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Abbreviations.setFont(font)
        self.Abbreviations.setObjectName("Abbreviations")
        self.Logo_GFM = QtWidgets.QLabel(self.centralwidget)
        self.Logo_GFM.setGeometry(QtCore.QRect(30, 40, 81, 81))
        self.Logo_GFM.setText("")
        self.Logo_GFM.setPixmap(QtGui.QPixmap("../Img/gsm_1.jpg"))
        self.Logo_GFM.setScaledContents(True)
        self.Logo_GFM.setObjectName("Logo_GFM")
        self.Logo_Telematics = QtWidgets.QLabel(self.centralwidget)
        self.Logo_Telematics.setGeometry(QtCore.QRect(550, 40, 151, 71))
        self.Logo_Telematics.setTabletTracking(False)
        self.Logo_Telematics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Logo_Telematics.setAcceptDrops(False)
        self.Logo_Telematics.setText("")
        self.Logo_Telematics.setPixmap(QtGui.QPixmap("../Img/Telematics.png"))
        self.Logo_Telematics.setScaledContents(True)
        self.Logo_Telematics.setObjectName("Logo_Telematics")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 350, 131, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Img/Uptc_Logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">DETERMINATION OF CRITICAL </span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">PARAMETERS FROM THE STUDY OF</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">MAGNETIC FLUCTUACTIONS </span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">IN HTCS  </span></p></body></html>"))
        self.Description.setText(_translate("mainWindow", "Description of the Theoretical Model"))
        self.DataEntry.setText(_translate("mainWindow", "Data Entry"))
        self.SoftwareDescription.setText(_translate("mainWindow", "Software Description "))
        self.Abbreviations.setText(_translate("mainWindow", "Abbreviations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

